# --- (Opcionális) API proxy példa ---
[[redirects]]
  from = "/api/gemini-proxy"
  to = "https://VALODI-SZERVER.DOMAIN/api/v1/endpoint"
  status = 200
  force = true

# --- Netlify Image CDN: engedélyezett TÁVOLI képek (Firebase Storage) ---
[images]
remote_images = [
  # Firebase bucket
  "https://firebasestorage.googleapis.com/v0/b/orelexa-gardrob.firebasestorage.app/*",
  # jsDelivr (itt voltak a 400-as hibák)
  "https://cdn.jsdelivr.net/*"
]


# --- Cache fejek ---
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/**/*.@(jpg|jpeg|png|gif|webp|avif|svg)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
